namespace Plang.Compiler.Backend.PInfer
{
    internal class PreambleConstants
    {
        internal static string StaticMethods = @"
            @FunctionalInterface
            private interface TriPredicate<A, B, C> {
                boolean test(A a, B b, C c);
            }
            public static bool eq(Object o1, Object o2) {
                return Objects.equals(o1, o2);
            }
        ";

        public static void WriteBeginClassDefn(CompiledFile fp, CompilationContext ctx)
        {
            fp.Stream.WriteLine("// This file was automatically generated by PInfer.");
            fp.Stream.WriteLine($"public class {ctx.ProjectName} {{");
            fp.Stream.WriteLine(StaticMethods);
        }
    }
}