[
uuid(1de89548-cb84-450f-b929-40779316e715),
version(1.0)
]
interface StartMachine
{
    void WrapSmfNew(handle_t startMachine_IfHandle, [in] long InstanceOf);
    void WrapSmfEnqueueEvent(handle_t startMachine_IfHandle, [in] long EventIndex);
    void ChildUp(handle_t startMachine_IfHandle);
    void MachineShutdown(handle_t startMachine_IfHandle);
}

