[
	uuid(563ae8a2-1f4b-4ac0-9331-9ae33f517a35),
	version(1.0),
	pointer_default(ptr)
]
interface PrtDistNodeManager
{
	void PrtDistNMPing(
		[in] handle_t myHandle,
		[in] int server,
		[out] boolean* status);


	void PrtDistNMCreateContainer(
		[in] handle_t myHandle,
		[out] int* containerId,
		[out] boolean *status
		);


	void PrtDistCentralServerGetNodeId(
		[in] handle_t myHandle,
		[in] int sourceServer,
		[out] int *nodeId
		);
}