[
	uuid(6f15af3b-0784-4fe4-a512-02e9006cf660),
	version(1.0),
	pointer_default(ptr)
]

interface PrtDist {

	import "PrtValues_IDL.idl";

	/******************************/
	//		RPC Functions
	/*****************************/
	//this function sends the event asynchronously.
	void PrtDistSendEx(
		[in] handle_t handleSM,
		[in] PRT_VALUE* source,
		[in] PRT_INT64 seqNum,
		[in] PRT_VALUE* target,
		[in, ptr] PRT_VALUE* event,
		[in, ptr] PRT_VALUE* payload
	);

	void PrtDistMkMachine(
		[in] handle_t handleSM,
		[in] PRT_INT32 instanceOf,
		[in, ptr] PRT_VALUE* params,
		[in, out] PRT_VALUE** retVal
	);

	
}

