#ifndef PRTDISTGLOBALINFO_H
#define PRTDISTGLOBALINFO_H

int PRTD_SERVICE_PORT = 5300;
int PRTD_CONTAINER_RECV_PORT = 5600;
int PRTD_CENTRALSERVER_NODEID = 0;

//this array stores the computer-name or ipaddress using which the machines can be addressed.
char* PRTD_CLUSTERMACHINES[] =
{
	"LOCALHOST",
	"PLANGDIST1",
	"PLANGDIST2",
	"PLANGDIST3",
	"PLANGDIST4",
	"PLANGDIST5",
	"PLANGDIST6",
	"PLANGDIST7",
	"PLANGDIST8",
	"PLANGDIST9",
	"PLANGDIST10"
};

#endif