#ifndef PRTDISTGLOBALINFO_H
#define PRTDISTGLOBALINFO_H

#define PRTD_CENTRALSERVER_NODEID 0

enum AzureMachines {
	LOCALHOST = 0,
	PLANGDIST_1,
	PLANGDIST_2,
	PLANGDIST_3,
	PLANGDIST_4,
	PLANGDIST_5,
	PLANGDIST_6,
	PLANGDIST_7,
	PLANGDIST_8,
	PLANGDIST_9,
	PLANGDIST_10,
	TOTAL_NODES = 10
};

//this array stores the computer-name or ipaddress using which the machines can be addressed.
char* AZUREMACHINEREF[] =
{
	"LOCALHOST",
	"PLANGDIST1",
	"PLANGDIST2",
	"PLANGDIST3",
	"PLANGDIST4",
	"PLANGDIST5",
	"PLANGDIST6",
	"PLANGDIST7",
	"PLANGDIST8",
	"PLANGDIST9",
	"PLANGDIST10"
};

#endif