[
uuid(ec966b88-c0b1-4d9e-a764-c14d494345c8),
version(1.0)
]
interface Manager
{
    void NewMachineId([out] long *addressSize, [out, size_is(, *addressSize)] char **address, [out] long *portSize, [out, size_is(, *portSize)] char **port);
    void ManagerShutdown(void);
}

