#define PRTD_SERVICE_PORT 4500
#define PRTD_CENTRALSERVER_PORT 5500
#define PRTD_START_NODEMANAGER_TCPPORT 4700

enum AzureMachines {
	LOCALHOST = 0,
	PLANGDIST_1,
	PLANGDIST_2,
	PLANGDIST_3,
	PLANGDIST_4,
	PLANGDIST_5,
	PLANGDIST_6,
	PLANGDIST_7,
	PLANGDIST_8,
	PLANGDIST_9,
	PLANGDIST_10,
	TOTAL_NODES = 4
};


char* AZUREMACHINE_NAMES[] =
{
	"LOCALHOST",
	"PLANGDIST1",
	"PLANGDIST2",
	"PLANGDIST3",
	"PLANGDIST4",
	"PLANGDIST5",
	"PLANGDIST6",
	"PLANGDIST7",
	"PLANGDIST8",
	"PLANGDIST9",
	"PLANGDIST10"
};