[
	uuid(186eb9f0-82f7-43de-97da-34b36dee1a32),
	version(1.0)
]

interface PrtRPCSerializationTest
{
	import "PrtValues_IDL.idl";

	//Test function send prtvalues
	void PrtRPCTestSend(
		[in] handle_t handleM,
		[in, ptr] PRT_VALUE* value
		);
}