site_name: 'P'
site_description: 'P: Modular and Safe Programming of Distributed Systems'
site_author: 'Ankush Desai'

theme:
  name: windmill
  logo: icon.png
# This should be renamed to nav for mkdocs 1.0+
nav:
- P: index.md
- How does P work: howdoesitwork.md
- Getting Started:
  - Installing P: getstarted/install.md
  - Building from Source: getstarted/build.md
  - Syntax Highlighting for P: getstarted/syntaxhighlight.md
  - Simple client server application using P: getstarted/clientserver.md
- Publications: publications.md
- Case Studies: casestudies.md
- Blogs and Articles: articles.md
- Videos: videos.md
- Tutorials:
    - Outline: tutsoutline.md
    - Client Server: tutorial/clientserver.md
    - Two Phase Commit: tutorial/twophasecommit.md
    - Failure Detector: tutorial/paxos.md
    - Paxos Made Simple: tutorial/paxos.md
- How-to guides:
    - Modeling Shared Memory Concurrency: howtoguides/sharedmemory.md
    - Model based testing of implementation: howtoguides/modelbasedtesting.md
    - Importance of Liveness Specifications: howtoguides/importanceliveness.md
- FAQ: faq.md
- Language Manual:
    - P Events: manual/events.md
    - P State Machines: manual/statemachines.md
    - P Monitors: manual/monitors.md
    - P Functions: manual/functions.md
    - P Statements: manual/functions.md
    - P DataTypes and Operations: manual/functions.md
    - P Module System: manual/functions.md
    - P Test cases: manual/functions.md
    - P Foreign Interface: manual/functions.md


markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - footnotes: