site_name: 'P'
site_url: http://p-org.github.io/P/
site_description: 'P: Modular and Safe Programming of Distributed Systems'
site_author: 'Ankush Desai'

repo_url: https://github.com/p-org/P
repo_name: P on Github
edit_uri: ""

theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: deep orange
  logo: ./icon.png
  favicon: ./icon.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.expand
    - navigation.top
    - toc.integrate



# This should be renamed to nav for mkdocs 1.0+
nav:
- Home: index.md
- How does P work: howdoesitwork.md
- Getting Started:
  - Installing P: getstarted/install.md
  - Building from Source: getstarted/build.md
  - Syntax Highlighting for P: getstarted/syntaxhighlight.md
  - Using P Compiler and Checker: getstarted/clientserver.md
- Tutorials:
    - Outline: tutsoutline.md
    - Client Server: tutorial/clientserver.md
    - Two Phase Commit: tutorial/twophasecommit.md
    - Failure Detector: tutorial/paxos.md
    - Paxos Made Simple: tutorial/paxos.md
- How-to guides:
    - Modeling Shared Memory Concurrency: howtoguides/sharedmemory.md
    - Model based testing of implementation: howtoguides/modelbasedtesting.md
    - Importance of Liveness Specifications: howtoguides/importanceliveness.md
- Publications: publications.md
- Case Studies: casestudies.md
- Blogs and Articles: articles.md
- Videos: videos.md
- Language Manual:
    - Outline: manualoutline.md
    - P Events: manual/events.md
    - P State Machines: manual/statemachines.md
    - P Monitors: manual/monitors.md
    - P Functions: manual/functions.md
    - P Statements: manual/functions.md
    - P DataTypes and Operations: manual/functions.md
    - P Module System: manual/functions.md
    - P Test cases: manual/functions.md
    - P Foreign Interface: manual/functions.md


markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.highlight
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid-experimental
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      toc_depth: 4

plugins:
  - search:
      prebuild_index: true

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_planguage
      name: P on Twitter
    - icon: fontawesome/solid/paper-plane
      link: mailto:ankushdesai@gmail.com
      name: Contact P Team
  analytics:
    provider: google
    property: G-0WWG87T6BN

copyright: Copyright &copy; 2021 P Developers