site_name: "P"
site_url: https://p-org.github.io/P/
site_description: "P: Modular and Safe Programming of Distributed Systems"
site_author: "Ankush Desai"

repo_url: https://github.com/p-org/P
repo_name: P on Github
edit_uri: ""

theme:
  language: en
  name: material
  palette:
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: ./icon.png
  favicon: ./icon.png
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link
    - toc.follow

nav:
  - Home: index.md
  - What is P?: whatisP.md
  - Getting Started:
      - Installing P: getstarted/install.md
      - PeasyAI - AI for P: getstarted/peasyai.md
      - Peasy - IDE for P: getstarted/PeasyIDE.md
      - Using P Compiler and Checker: getstarted/usingP.md

  - Tutorials:
      - Outline: tutsoutline.md
      - Client Server: tutorial/clientserver.md
      - Two Phase Commit: tutorial/twophasecommit.md
      - Espresso Machine: tutorial/espressomachine.md
      - Failure Detector: tutorial/failuredetector.md
      - Single Decree Paxos: tutorial/paxos.md
      - Timer, Failure, and Shared Memory: tutorial/common.md
  - Advanced:
      - P Semantics: advanced/psemantics.md
      - Liveness Specifications: advanced/importanceliveness.md
      - Program Structure: advanced/structureOfPProgram.md
      - Project File: advanced/PProject.md
      - Debugging Error Traces: advanced/debuggingerror.md
      - PEx (Exhaustive Checking): advanced/pex.md
      - "PObserve: Runtime Monitoring":
        - Overview: advanced/pobserve/pobserve.md
        - Getting Started: advanced/pobserve/gettingstarted.md
        - Package Setup: advanced/pobserve/package-setup.md
        - Writing a Log Parser: advanced/pobserve/logparser.md
        - JUnit Integration: advanced/pobserve/pobservejunit.md
        - CLI Integration: advanced/pobserve/pobservecli.md
        - "Example: Lock Server":
          - Overview: advanced/pobserve/example/lockserver.md
          - With PObserve JUnit: advanced/pobserve/example/lockserverwithpobservejunit.md
          - With PObserve CLI: advanced/pobserve/example/lockserverwithpobservecli.md
      - "PVerifier: Formal Proofs":
        - Announcement: advanced/PVerifierLanguageExtensions/announcement.md
        - Outline: advanced/PVerifierLanguageExtensions/outline.md
        - Installation: advanced/PVerifierLanguageExtensions/install-pverifier.md
        - Using PVerifier: advanced/PVerifierLanguageExtensions/using-pverifier.md
        - Pure Functions: advanced/PVerifierLanguageExtensions/pure.md
        - Init Conditions: advanced/PVerifierLanguageExtensions/init-condition.md
        - Specifications: advanced/PVerifierLanguageExtensions/specification.md
        - Lemmas and Proofs: advanced/PVerifierLanguageExtensions/proof.md
        - "Example: Two Phase Commit": advanced/PVerifierLanguageExtensions/twophasecommitverification.md
  - Language Manual:
      - P Program (Outline): manualoutline.md
      - P DataTypes: manual/datatypes.md
      - P Events: manual/events.md
      - P State Machines: manual/statemachines.md
      - P Monitors: manual/monitors.md
      - P Functions: manual/functions.md
      - P Expressions: manual/expressions.md
      - P Statements: manual/statements.md
      - P Module System: manual/modulesystem.md
      - P Test cases: manual/testcases.md
      - P Foreign Interface: manual/foreigntypesfunctions.md
  - Case Studies: casestudies.md
  - Publications:
      - Papers: publications.md
      - Videos: videos.md
  - Contributing:
      - Building from Source: getstarted/build.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - search:
      separator: '[\s\-\.]+'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/_planguage
      name: P on Twitter
    - icon: fontawesome/solid/paper-plane
      link: mailto:ankushdesai@gmail.com
      name: Contact P Team
  analytics:
    provider: google
    property: G-0WWG87T6BN

copyright: Copyright &copy; 2026 P Developers
