<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>p</string>
	</array>
	<key>name</key>
	<string>P language</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\bif\b|\belse\b|\bwhile\b|\breturn\b|\bgoto\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bvar\b</string>
			<key>name</key>
			<string>keyword</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bassert\b|\bassume\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bsatisfies\b|\bmonitors\b|\bspec\b|\binclude\b|\bfun\b|\bnull\b|\bsizeof\b|\bpublic\b|\bin\b|\bdefault\b|\bdo\b|\bwith\b|\bevent\b|\binterface\b|\bmodule\b|\btype\b|\bsends\b|\bcreates\b|\bmachine\b|\breceives\b|\bstate\b|\bon\b|\bgoto\b|\bignore\b|\bdefer\b|\bmonitor\b|\bobserves\b|\bcold\b|\bhot\b|\bmain\b|\bmodel\b|\btest\b|\bsafety\b|\bimplementation\b|\bpush\b|\bnew\b|\bprint\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bstart\b</string>
			<key>name</key>
			<string>keyword.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bentry\b|\bexit\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bsend\b|\braise\b</string>
			<key>name</key>
			<string>support.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\be[A-Z]\w*\b</string>
			<key>name</key>
			<string>string.regexp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\w*Machine\b|\bM[A-Z]\w*\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\w*Interface\b|\bI[A-Z]\w*\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\w\w*Type\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bint\b|\bbool\b|\bseq\b|\bmap\b|\bany\b|\bforeign\b</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\w*V\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bthis\b</string>
			<key>name</key>
			<string>support.constant</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b|\bfalse\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.p</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.p</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(//).*$\n?</string>
			<key>name</key>
			<string>comment.line.double-slash</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.p</string>
	<key>uuid</key>
	<string>02d90f6f-553b-4a22-a121-a8ddeb6dade4</string>
</dict>
</plist>
