# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on:
  push:
    branches: [ "maven-publish-**" ]
  workflow_dispatch:

jobs:
  Maven-Publish-Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#      - name: Configure GPG Key
#        run: |
#          echo -n "$GPG_PRIVATE_KEY" | base64 | base64 --decode | gpg --import
#        env:
#          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
#      - name: Import GPG key
#        id: import_gpg
#        uses: crazy-max/ghaction-import-gpg@v4
#        with:
#          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
#          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
#          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Configure GPG Key
        run: |
          mkdir -p ~/.gnupg/
          print "${GPG_PRIVATE_KEY}" | base64 | base64 --decode > ~/.gnupg/private.key
          gpg --batch --passphrase ${GPG_PASSPHRASE} --import ~/.gnupg/private.key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish package
        working-directory: Src/PRuntimes/PSymRuntime
        run: |
          mvn --batch-mode deploy -P release -Dmaven.test.skip
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
