name: Publish Docs
on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: Docs/requirements.txt
      - name: Install MkDocs
        run: pip install -r Docs/requirements.txt
      - name: MkDocs build
        working-directory: ./Docs
        run: mkdocs build
      - name: MkDocs deploy
        working-directory: ./Docs
        run: mkdocs gh-deploy --force
